// Generated by Bisonc++ V2.09.03 on Tue, 11 Mar 2014 00:59:47 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {296, 2}, // 1: program ->  func_decl_statement_list procedure_list
     {296, 3}, // 2: program ->  declaration_statement_list func_decl_statement_list procedure_list
     {296, 1}, // 3: program ->  procedure_list
     {298, 2}, // 4: procedure_list ->  procedure_list procedure_fun
     {298, 1}, // 5: procedure_list ->  procedure_fun
     {299, 3}, // 6: procedure_fun ->  procedure_name #0001 procedure_body
     {302, 0}, // 7: #0001 ->  <empty>
     {300, 4}, // 8: procedure_name (NAME) ->  NAME '(' parameter_statement_list ')'
     {301, 5}, // 9: procedure_body ('{') ->  '{' declaration_statement_list #0002 basic_block_list '}'
     {303, 0}, // 10: #0002 ->  <empty>
     {301, 3}, // 11: procedure_body ('{') ->  '{' basic_block_list '}'
     {304, 1}, // 12: declaration_statement_list ->  declaration_statement
     {304, 2}, // 13: declaration_statement_list ->  declaration_statement_list declaration_statement
     {297, 2}, // 14: func_decl_statement_list ->  func_decl_statement_list function_declaration
     {297, 1}, // 15: func_decl_statement_list ->  function_declaration
     {305, 6}, // 16: function_declaration (INTEGER) ->  INTEGER NAME '(' parameter_statement_list ')' ';'
     {305, 6}, // 17: function_declaration (FLOAT) ->  FLOAT NAME '(' parameter_statement_list ')' ';'
     {305, 6}, // 18: function_declaration (VOID) ->  VOID NAME '(' parameter_statement_list ')' ';'
     {306, 1}, // 19: parameter_statement_list ->  parameter_statement
     {306, 3}, // 20: parameter_statement_list (',') ->  parameter_statement_list ',' parameter_statement
     {307, 2}, // 21: parameter_statement (INTEGER) ->  INTEGER NAME
     {307, 2}, // 22: parameter_statement (FLOAT) ->  FLOAT NAME
     {307, 0}, // 23: parameter_statement ->  <empty>
     {308, 3}, // 24: declaration_statement (INTEGER) ->  INTEGER NAME ';'
     {308, 3}, // 25: declaration_statement (FLOAT) ->  FLOAT NAME ';'
     {309, 2}, // 26: basic_block_list ->  basic_block_list basic_block
     {309, 1}, // 27: basic_block_list ->  basic_block
     {310, 3}, // 28: basic_block (BASIC_BLOCK) ->  BASIC_BLOCK ':' executable_statement_list
     {311, 1}, // 29: executable_statement_list ->  assignment_statement_list
     {311, 3}, // 30: executable_statement_list (RETURN) ->  assignment_statement_list RETURN ';'
     {311, 4}, // 31: executable_statement_list (RETURN) ->  assignment_statement_list RETURN for_precedence ';'
     {311, 2}, // 32: executable_statement_list ->  assignment_statement_list if_statement
     {311, 2}, // 33: executable_statement_list ->  assignment_statement_list goto_statement
     {312, 11}, // 34: if_statement (IF) ->  IF '(' for_precedence ')' GOTO BASIC_BLOCK ';' ELSE GOTO BASIC_BLOCK ';'
     {313, 3}, // 35: goto_statement (GOTO) ->  GOTO BASIC_BLOCK ';'
     {314, 1}, // 36: relational_expression ->  arithmetic_expression
     {314, 3}, // 37: relational_expression (LE) ->  relational_expression LE relational_expression
     {314, 3}, // 38: relational_expression (GE) ->  relational_expression GE relational_expression
     {314, 3}, // 39: relational_expression (LT) ->  relational_expression LT relational_expression
     {314, 3}, // 40: relational_expression (GT) ->  relational_expression GT relational_expression
     {315, 3}, // 41: arithmetic_expression ('+') ->  arithmetic_expression '+' arithmetic_expression
     {315, 3}, // 42: arithmetic_expression ('-') ->  arithmetic_expression '-' arithmetic_expression
     {315, 3}, // 43: arithmetic_expression ('*') ->  arithmetic_expression '*' arithmetic_expression
     {315, 3}, // 44: arithmetic_expression ('/') ->  arithmetic_expression '/' arithmetic_expression
     {315, 1}, // 45: arithmetic_expression ->  unary_expression
     {315, 3}, // 46: arithmetic_expression ('(') ->  '(' for_precedence ')'
     {315, 1}, // 47: arithmetic_expression ->  any
     {316, 2}, // 48: unary_expression ('-') ->  '-' any
     {316, 4}, // 49: unary_expression ('-') ->  '-' '(' for_precedence ')'
     {316, 6}, // 50: unary_expression ('(') ->  '(' FLOAT ')' '(' arithmetic_expression ')'
     {316, 6}, // 51: unary_expression ('(') ->  '(' DOUBLE ')' '(' arithmetic_expression ')'
     {316, 6}, // 52: unary_expression ('(') ->  '(' INTEGER ')' '(' arithmetic_expression ')'
     {316, 4}, // 53: unary_expression ('(') ->  '(' FLOAT ')' any
     {316, 4}, // 54: unary_expression ('(') ->  '(' DOUBLE ')' any
     {316, 4}, // 55: unary_expression ('(') ->  '(' INTEGER ')' any
     {317, 1}, // 56: for_precedence ->  relational_expression
     {317, 3}, // 57: for_precedence (NE) ->  for_precedence NE for_precedence
     {317, 3}, // 58: for_precedence (EQ) ->  for_precedence EQ for_precedence
     {318, 0}, // 59: assignment_statement_list ->  <empty>
     {318, 2}, // 60: assignment_statement_list ->  assignment_statement_list assignment_statement
     {319, 1}, // 61: arg_list ->  for_precedence
     {319, 3}, // 62: arg_list (',') ->  arg_list ',' for_precedence
     {319, 0}, // 63: arg_list ->  <empty>
     {320, 4}, // 64: assignment_statement (ASSIGN_OP) ->  variable1 ASSIGN_OP for_precedence ';'
     {320, 5}, // 65: assignment_statement (NAME) ->  NAME '(' arg_list ')' ';'
     {321, 1}, // 66: variable1 (NAME) ->  NAME
     {322, 1}, // 67: variable ->  variable1
     {322, 4}, // 68: variable (NAME) ->  NAME '(' arg_list ')'
     {323, 1}, // 69: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {323, 1}, // 70: constant (FLOAT_NUMBER) ->  FLOAT_NUMBER
     {324, 1}, // 71: any ->  variable
     {324, 1}, // 72: any ->  constant
     {325, 1}, // 73: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 13} },                              
    { {       296}, {  1} }, // program                   
    { {       297}, {  2} }, // func_decl_statement_list  
    { {       304}, {  3} }, // declaration_statement_list
    { {       298}, {  4} }, // procedure_list            
    { {       305}, {  5} }, // function_declaration      
    { {       308}, {  6} }, // declaration_statement     
    { {       299}, {  7} }, // procedure_fun             
    { {       262}, {  8} }, // INTEGER                   
    { {       263}, {  9} }, // FLOAT                     
    { {       265}, { 10} }, // VOID                      
    { {       300}, { 11} }, // procedure_name            
    { {       260}, { 12} }, // NAME                      
    { {         0}, {  0} },                              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, {  9} },                        
    { {       298}, { 13} }, // procedure_list      
    { {       305}, { 14} }, // function_declaration
    { {       299}, {  7} }, // procedure_fun       
    { {       262}, { 15} }, // INTEGER             
    { {       263}, { 16} }, // FLOAT               
    { {       265}, { 10} }, // VOID                
    { {       300}, { 11} }, // procedure_name      
    { {       260}, { 12} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, {  7} },                            
    { {       297}, { 17} }, // func_decl_statement_list
    { {       308}, { 18} }, // declaration_statement   
    { {       305}, {  5} }, // function_declaration    
    { {       262}, {  8} }, // INTEGER                 
    { {       263}, {  9} }, // FLOAT                   
    { {       265}, { 10} }, // VOID                    
    { {         0}, {  0} },                            
};

SR__ s_4[] =
{
    { { REQ_DEF}, {  4} },                  
    { {     299}, { 19} }, // procedure_fun 
    { {     300}, { 11} }, // procedure_name
    { {     260}, { 12} }, // NAME          
    { {       0}, { -3} },                  
};

SR__ s_5[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 20} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 21} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 22} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_11[] =
{
    { { DEF_RED}, {  2} },         
    { {     302}, { 23} }, // #0001
    { {       0}, { -7} },         
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 24} }, // '('
    { {         0}, {  0} },       
};

SR__ s_13[] =
{
    { { REQ_DEF}, {  4} },                  
    { {     299}, { 19} }, // procedure_fun 
    { {     300}, { 11} }, // procedure_name
    { {     260}, { 12} }, // NAME          
    { {       0}, { -1} },                  
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 25} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 26} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  9} },                        
    { {       298}, { 27} }, // procedure_list      
    { {       305}, { 14} }, // function_declaration
    { {       299}, {  7} }, // procedure_fun       
    { {       262}, { 15} }, // INTEGER             
    { {       263}, { 16} }, // FLOAT               
    { {       265}, { 10} }, // VOID                
    { {       300}, { 11} }, // procedure_name      
    { {       260}, { 12} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        40}, { 28} }, // '('
    { {        59}, { 29} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        40}, { 30} }, // '('
    { {        59}, { 31} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 32} }, // '('
    { {         0}, {  0} },       
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       301}, { 33} }, // procedure_body
    { {       123}, { 34} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_24[] =
{
    { { REQ_DEF}, {   5} },                            
    { {     306}, {  35} }, // parameter_statement_list
    { {     307}, {  36} }, // parameter_statement     
    { {     262}, {  37} }, // INTEGER                 
    { {     263}, {  38} }, // FLOAT                   
    { {       0}, { -23} },                            
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 28} }, // '('
    { {         0}, {  0} },       
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 30} }, // '('
    { {         0}, {  0} },       
};

SR__ s_27[] =
{
    { { REQ_DEF}, {  4} },                  
    { {     299}, { 19} }, // procedure_fun 
    { {     300}, { 11} }, // procedure_name
    { {     260}, { 12} }, // NAME          
    { {       0}, { -2} },                  
};

SR__ s_28[] =
{
    { { REQ_DEF}, {   5} },                            
    { {     306}, {  39} }, // parameter_statement_list
    { {     307}, {  36} }, // parameter_statement     
    { {     262}, {  37} }, // INTEGER                 
    { {     263}, {  38} }, // FLOAT                   
    { {       0}, { -23} },                            
};

SR__ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_30[] =
{
    { { REQ_DEF}, {   5} },                            
    { {     306}, {  40} }, // parameter_statement_list
    { {     307}, {  36} }, // parameter_statement     
    { {     262}, {  37} }, // INTEGER                 
    { {     263}, {  38} }, // FLOAT                   
    { {       0}, { -23} },                            
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_32[] =
{
    { { REQ_DEF}, {   5} },                            
    { {     306}, {  41} }, // parameter_statement_list
    { {     307}, {  36} }, // parameter_statement     
    { {     262}, {  37} }, // INTEGER                 
    { {     263}, {  38} }, // FLOAT                   
    { {       0}, { -23} },                            
};

SR__ s_33[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  8} },                              
    { {       304}, { 42} }, // declaration_statement_list
    { {       309}, { 43} }, // basic_block_list          
    { {       308}, {  6} }, // declaration_statement     
    { {       310}, { 44} }, // basic_block               
    { {       262}, { 45} }, // INTEGER                   
    { {       263}, { 46} }, // FLOAT                     
    { {       258}, { 47} }, // BASIC_BLOCK               
    { {         0}, {  0} },                              
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 48} }, // ')'
    { {        44}, { 49} }, // ','
    { {         0}, {  0} },       
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 50} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 51} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 52} }, // ')'
    { {        44}, { 49} }, // ','
    { {         0}, {  0} },       
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 53} }, // ')'
    { {        44}, { 49} }, // ','
    { {         0}, {  0} },       
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 54} }, // ')'
    { {        44}, { 49} }, // ','
    { {         0}, {  0} },       
};

SR__ s_42[] =
{
    { { REQ_DEF}, {   5} },                         
    { {     303}, {  55} }, // #0002                
    { {     308}, {  18} }, // declaration_statement
    { {     262}, {  45} }, // INTEGER              
    { {     263}, {  46} }, // FLOAT                
    { {       0}, { -10} },                         
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 56} }, // '}'        
    { {       310}, { 57} }, // basic_block
    { {       258}, { 47} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 58} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 59} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        58}, { 60} }, // ':'
    { {         0}, {  0} },       
};

SR__ s_48[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_49[] =
{
    { { REQ_DEF}, {   4} },                       
    { {     307}, {  61} }, // parameter_statement
    { {     262}, {  37} }, // INTEGER            
    { {     263}, {  38} }, // FLOAT              
    { {       0}, { -23} },                       
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 62} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 63} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 64} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       309}, { 65} }, // basic_block_list
    { {       310}, { 44} }, // basic_block     
    { {       258}, { 47} }, // BASIC_BLOCK     
    { {         0}, {  0} },                    
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 29} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 31} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_60[] =
{
    { { DEF_RED}, {   3} },                             
    { {     311}, {  66} }, // executable_statement_list
    { {     318}, {  67} }, // assignment_statement_list
    { {       0}, { -59} },                             
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 68} }, // '}'        
    { {       310}, { 57} }, // basic_block
    { {       258}, { 47} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_67[] =
{
    { { REQ_DEF}, {   9} },                        
    { {     261}, {  69} }, // RETURN              
    { {     312}, {  70} }, // if_statement        
    { {     313}, {  71} }, // goto_statement      
    { {     320}, {  72} }, // assignment_statement
    { {     266}, {  73} }, // IF                  
    { {     268}, {  74} }, // GOTO                
    { {     321}, {  75} }, // variable1           
    { {     260}, {  76} }, // NAME                
    { {       0}, { -29} },                        
};

SR__ s_68[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, { 15} },                         
    { {        59}, { 77} }, // ';'                  
    { {       317}, { 78} }, // for_precedence       
    { {       314}, { 79} }, // relational_expression
    { {       315}, { 80} }, // arithmetic_expression
    { {       316}, { 81} }, // unary_expression     
    { {        40}, { 82} }, // '('                  
    { {       324}, { 83} }, // any                  
    { {        45}, { 84} }, // '-'                  
    { {       322}, { 85} }, // variable             
    { {       323}, { 86} }, // constant             
    { {       321}, { 87} }, // variable1            
    { {       260}, { 88} }, // NAME                 
    { {       257}, { 89} }, // INTEGER_NUMBER       
    { {       259}, { 90} }, // FLOAT_NUMBER         
    { {         0}, {  0} },                         
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 91} }, // '('
    { {         0}, {  0} },       
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       258}, { 92} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       269}, { 93} }, // ASSIGN_OP
    { {         0}, {  0} },             
};

SR__ s_76[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, {  94} }, // '('
    { {       0}, { -66} },       
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  4} },       
    { {        59}, { 95} }, // ';'
    { {       291}, { 96} }, // NE 
    { {       290}, { 97} }, // EQ 
    { {         0}, {  0} },       
};

SR__ s_79[] =
{
    { { REQ_DEF}, {   5} },      
    { {     295}, {  98} }, // LE
    { {     293}, {  99} }, // GE
    { {     294}, { 100} }, // LT
    { {     292}, { 101} }, // GT
    { {       0}, { -56} },      
};

SR__ s_80[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, { 102} }, // '+'
    { {      45}, { 103} }, // '-'
    { {      42}, { 104} }, // '*'
    { {      47}, { 105} }, // '/'
    { {       0}, { -36} },       
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  17} },                         
    { {       317}, { 106} }, // for_precedence       
    { {       263}, { 107} }, // FLOAT                
    { {       264}, { 108} }, // DOUBLE               
    { {       262}, { 109} }, // INTEGER              
    { {       314}, {  79} }, // relational_expression
    { {       315}, {  80} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, {   9} },                  
    { {       324}, { 110} }, // any           
    { {        40}, { 111} }, // '('           
    { {       322}, {  85} }, // variable      
    { {       323}, {  86} }, // constant      
    { {       321}, {  87} }, // variable1     
    { {       260}, {  88} }, // NAME          
    { {       257}, {  89} }, // INTEGER_NUMBER
    { {       259}, {  90} }, // FLOAT_NUMBER  
    { {         0}, {   0} },                  
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_88[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, { 112} }, // '('
    { {       0}, { -66} },       
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_90[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       317}, { 113} }, // for_precedence       
    { {       314}, {  79} }, // relational_expression
    { {       315}, {  80} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 114} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       317}, { 115} }, // for_precedence       
    { {       314}, {  79} }, // relational_expression
    { {       315}, {  80} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_94[] =
{
    { { REQ_DEF}, {  15} },                         
    { {     319}, { 116} }, // arg_list             
    { {     317}, { 117} }, // for_precedence       
    { {     314}, {  79} }, // relational_expression
    { {     315}, {  80} }, // arithmetic_expression
    { {     316}, {  81} }, // unary_expression     
    { {      40}, {  82} }, // '('                  
    { {     324}, {  83} }, // any                  
    { {      45}, {  84} }, // '-'                  
    { {     322}, {  85} }, // variable             
    { {     323}, {  86} }, // constant             
    { {     321}, {  87} }, // variable1            
    { {     260}, {  88} }, // NAME                 
    { {     257}, {  89} }, // INTEGER_NUMBER       
    { {     259}, {  90} }, // FLOAT_NUMBER         
    { {       0}, { -63} },                         
};

SR__ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       317}, { 118} }, // for_precedence       
    { {       314}, {  79} }, // relational_expression
    { {       315}, {  80} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       317}, { 119} }, // for_precedence       
    { {       314}, {  79} }, // relational_expression
    { {       315}, {  80} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {  13} },                         
    { {       314}, { 120} }, // relational_expression
    { {       315}, {  80} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {  13} },                         
    { {       314}, { 121} }, // relational_expression
    { {       315}, {  80} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {  13} },                         
    { {       314}, { 122} }, // relational_expression
    { {       315}, {  80} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {  13} },                         
    { {       314}, { 123} }, // relational_expression
    { {       315}, {  80} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {  12} },                         
    { {       315}, { 124} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {  12} },                         
    { {       315}, { 125} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {  12} },                         
    { {       315}, { 126} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_105[] =
{
    { { REQ_TOKEN}, {  12} },                         
    { {       315}, { 127} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_106[] =
{
    { { REQ_TOKEN}, {   4} },       
    { {        41}, { 128} }, // ')'
    { {       291}, {  96} }, // NE 
    { {       290}, {  97} }, // EQ 
    { {         0}, {   0} },       
};

SR__ s_107[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 129} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 130} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_109[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 131} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_110[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_111[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       317}, { 132} }, // for_precedence       
    { {       314}, {  79} }, // relational_expression
    { {       315}, {  80} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_112[] =
{
    { { REQ_DEF}, {  15} },                         
    { {     319}, { 133} }, // arg_list             
    { {     317}, { 117} }, // for_precedence       
    { {     314}, {  79} }, // relational_expression
    { {     315}, {  80} }, // arithmetic_expression
    { {     316}, {  81} }, // unary_expression     
    { {      40}, {  82} }, // '('                  
    { {     324}, {  83} }, // any                  
    { {      45}, {  84} }, // '-'                  
    { {     322}, {  85} }, // variable             
    { {     323}, {  86} }, // constant             
    { {     321}, {  87} }, // variable1            
    { {     260}, {  88} }, // NAME                 
    { {     257}, {  89} }, // INTEGER_NUMBER       
    { {     259}, {  90} }, // FLOAT_NUMBER         
    { {       0}, { -63} },                         
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {   4} },       
    { {        41}, { 134} }, // ')'
    { {       291}, {  96} }, // NE 
    { {       290}, {  97} }, // EQ 
    { {         0}, {   0} },       
};

SR__ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_115[] =
{
    { { REQ_TOKEN}, {   4} },       
    { {        59}, { 135} }, // ';'
    { {       291}, {  96} }, // NE 
    { {       290}, {  97} }, // EQ 
    { {         0}, {   0} },       
};

SR__ s_116[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        41}, { 136} }, // ')'
    { {        44}, { 137} }, // ','
    { {         0}, {   0} },       
};

SR__ s_117[] =
{
    { { REQ_DEF}, {   3} },      
    { {     291}, {  96} }, // NE
    { {     290}, {  97} }, // EQ
    { {       0}, { -61} },      
};

SR__ s_118[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_119[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_120[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_121[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_122[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_123[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_124[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 104} }, // '*'
    { {      47}, { 105} }, // '/'
    { {       0}, { -41} },       
};

SR__ s_125[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 104} }, // '*'
    { {      47}, { 105} }, // '/'
    { {       0}, { -42} },       
};

SR__ s_126[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_127[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_128[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_129[] =
{
    { { REQ_TOKEN}, {   9} },                  
    { {        40}, { 138} }, // '('           
    { {       324}, { 139} }, // any           
    { {       322}, {  85} }, // variable      
    { {       323}, {  86} }, // constant      
    { {       321}, {  87} }, // variable1     
    { {       260}, {  88} }, // NAME          
    { {       257}, {  89} }, // INTEGER_NUMBER
    { {       259}, {  90} }, // FLOAT_NUMBER  
    { {         0}, {   0} },                  
};

SR__ s_130[] =
{
    { { REQ_TOKEN}, {   9} },                  
    { {        40}, { 140} }, // '('           
    { {       324}, { 141} }, // any           
    { {       322}, {  85} }, // variable      
    { {       323}, {  86} }, // constant      
    { {       321}, {  87} }, // variable1     
    { {       260}, {  88} }, // NAME          
    { {       257}, {  89} }, // INTEGER_NUMBER
    { {       259}, {  90} }, // FLOAT_NUMBER  
    { {         0}, {   0} },                  
};

SR__ s_131[] =
{
    { { REQ_TOKEN}, {   9} },                  
    { {        40}, { 142} }, // '('           
    { {       324}, { 143} }, // any           
    { {       322}, {  85} }, // variable      
    { {       323}, {  86} }, // constant      
    { {       321}, {  87} }, // variable1     
    { {       260}, {  88} }, // NAME          
    { {       257}, {  89} }, // INTEGER_NUMBER
    { {       259}, {  90} }, // FLOAT_NUMBER  
    { {         0}, {   0} },                  
};

SR__ s_132[] =
{
    { { REQ_TOKEN}, {   4} },       
    { {        41}, { 144} }, // ')'
    { {       291}, {  96} }, // NE 
    { {       290}, {  97} }, // EQ 
    { {         0}, {   0} },       
};

SR__ s_133[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        41}, { 145} }, // ')'
    { {        44}, { 137} }, // ','
    { {         0}, {   0} },       
};

SR__ s_134[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       268}, { 146} }, // GOTO
    { {         0}, {   0} },        
};

SR__ s_135[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_136[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 147} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_137[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       317}, { 148} }, // for_precedence       
    { {       314}, {  79} }, // relational_expression
    { {       315}, {  80} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_138[] =
{
    { { REQ_TOKEN}, {  12} },                         
    { {       315}, { 149} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_139[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_140[] =
{
    { { REQ_TOKEN}, {  12} },                         
    { {       315}, { 150} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_141[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_142[] =
{
    { { REQ_TOKEN}, {  12} },                         
    { {       315}, { 151} }, // arithmetic_expression
    { {       316}, {  81} }, // unary_expression     
    { {        40}, {  82} }, // '('                  
    { {       324}, {  83} }, // any                  
    { {        45}, {  84} }, // '-'                  
    { {       322}, {  85} }, // variable             
    { {       323}, {  86} }, // constant             
    { {       321}, {  87} }, // variable1            
    { {       260}, {  88} }, // NAME                 
    { {       257}, {  89} }, // INTEGER_NUMBER       
    { {       259}, {  90} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_143[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_144[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_145[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_146[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       258}, { 152} }, // BASIC_BLOCK
    { {         0}, {   0} },               
};

SR__ s_147[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_148[] =
{
    { { REQ_DEF}, {   3} },      
    { {     291}, {  96} }, // NE
    { {     290}, {  97} }, // EQ
    { {       0}, { -62} },      
};

SR__ s_149[] =
{
    { { REQ_TOKEN}, {   6} },       
    { {        41}, { 153} }, // ')'
    { {        43}, { 102} }, // '+'
    { {        45}, { 103} }, // '-'
    { {        42}, { 104} }, // '*'
    { {        47}, { 105} }, // '/'
    { {         0}, {   0} },       
};

SR__ s_150[] =
{
    { { REQ_TOKEN}, {   6} },       
    { {        41}, { 154} }, // ')'
    { {        43}, { 102} }, // '+'
    { {        45}, { 103} }, // '-'
    { {        42}, { 104} }, // '*'
    { {        47}, { 105} }, // '/'
    { {         0}, {   0} },       
};

SR__ s_151[] =
{
    { { REQ_TOKEN}, {   6} },       
    { {        41}, { 155} }, // ')'
    { {        43}, { 102} }, // '+'
    { {        45}, { 103} }, // '-'
    { {        42}, { 104} }, // '*'
    { {        47}, { 105} }, // '/'
    { {         0}, {   0} },       
};

SR__ s_152[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 156} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_153[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_154[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_155[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_156[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       267}, { 157} }, // ELSE
    { {         0}, {   0} },        
};

SR__ s_157[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       268}, { 158} }, // GOTO
    { {         0}, {   0} },        
};

SR__ s_158[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       258}, { 159} }, // BASIC_BLOCK
    { {         0}, {   0} },               
};

SR__ s_159[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 160} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_160[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,  s_153,  s_154,  s_155,  s_156,  s_157,  s_158,  s_159,
  s_160,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
        {
         
         
         
         }
        break;

        case 2:
        {
         
         program_object.set_global_table(*d_vsp__[-2].symbol_table);
         if (!d_vsp__[-2].symbol_table)
         report_internal_error("parsing wrong");
         d_vsp__[-2].symbol_table->global_list_in_proc_map_check(get_line_number()); 
         delete d_vsp__[-2].symbol_table ;
         
         }
        break;

        case 3:
        {
         
         
         
         }
        break;

        case 6:
        {
         
         
         
         
         }
        break;

        case 7:
        d_val__ = d_vsp__[0];
        {
         return_statement_used_flag = false;
         }
        break;

        case 8:
        {
         
         if (*d_vsp__[-3].string_value == "main"){
         current_procedure = new Procedure(void_data_type, *d_vsp__[-3].string_value, *d_vsp__[-1].symbol_entry_list);
         program_object.set_procedure_map(*current_procedure);
         }
         else {
         
         current_procedure = program_object.get_procedure(*d_vsp__[-3].string_value);
         }
         
         }
        break;

        case 9:
        {
         
         current_procedure->set_basic_block_list(*d_vsp__[-1].basic_block_list);
         delete d_vsp__[-1].basic_block_list;
         
         }
        break;

        case 10:
        d_val__ = d_vsp__[-1];
        {
         
         current_procedure->set_local_list(*d_vsp__[0].symbol_table);
         delete d_vsp__[0].symbol_table;
         
         }
        break;

        case 11:
        {
         
         current_procedure->set_basic_block_list(*d_vsp__[-1].basic_block_list);
         delete d_vsp__[-1].basic_block_list;
         
         }
        break;

        case 12:
        {
         
         int line = get_line_number();
         if (!d_vsp__[0].symbol_entry)
         report_error("declaration_statement cannot be null", line);
         program_object.variable_in_proc_map_check(d_vsp__[0].symbol_entry->get_variable_name(), line);
         string var_name = d_vsp__[0].symbol_entry->get_variable_name();
         if (current_procedure && current_procedure->get_proc_name() == var_name)
         report_error("Variable name cannot be same as procedure name", line);
         d_val__.symbol_table = new Symbol_Table();
         d_val__.symbol_table->push_symbol(d_vsp__[0].symbol_entry);
         
         }
        break;

        case 13:
        {
         
         
         
         int line = get_line_number();
         if (!d_vsp__[0].symbol_entry)
         report_error("declaration statement list cannot be null", line);
         program_object.variable_in_proc_map_check(d_vsp__[0].symbol_entry->get_variable_name(), line);
         string var_name = d_vsp__[0].symbol_entry->get_variable_name();
         if (current_procedure && current_procedure->get_proc_name() == var_name)
         report_error("Variable name cannot be same as procedure name", line);
         if (d_vsp__[-1].symbol_table)
         {
         if(d_vsp__[-1].symbol_table->variable_in_symbol_list_check(var_name))
         report_error("Variable is declared twice", line);
         d_val__.symbol_table = d_vsp__[-1].symbol_table;
         }
         else
         d_val__.symbol_table = new Symbol_Table();
         d_val__.symbol_table->push_symbol(d_vsp__[0].symbol_entry);
         
         }
        break;

        case 15:
        {
         
         
         }
        break;

        case 16:
        {
         
         Procedure *temp = new Procedure (int_data_type,*d_vsp__[-4].string_value,*d_vsp__[-2].symbol_entry_list);
         program_object.set_procedure_map(*temp);
         
         
         }
        break;

        case 17:
        {
         
         Procedure *temp = new Procedure (float_data_type,*d_vsp__[-4].string_value,*d_vsp__[-2].symbol_entry_list);
         program_object.set_procedure_map(*temp);
         
         
         }
        break;

        case 18:
        {
         
         Procedure *temp = new Procedure (void_data_type,*d_vsp__[-4].string_value,*d_vsp__[-2].symbol_entry_list);
         program_object.set_procedure_map(*temp);
         
         
         }
        break;

        case 19:
        {
         
         d_val__.symbol_entry_list=new list<Symbol_Table_Entry* >();
         d_val__.symbol_entry_list->push_back(d_vsp__[0].symbol_entry); 
         
         }
        break;

        case 20:
        {
         
         if (d_vsp__[-2].symbol_entry_list){
         d_val__.symbol_entry_list=d_vsp__[-2].symbol_entry_list;
         }
         else{
         d_val__.symbol_entry_list=new list<Symbol_Table_Entry* >();
         } 
         d_val__.symbol_entry_list->push_back(d_vsp__[0].symbol_entry); 
         
         }
        break;

        case 21:
        {
         
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[0].string_value,int_data_type);
         
         
         }
        break;

        case 22:
        {
         
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[0].string_value,float_data_type);
         
         }
        break;

        case 23:
        {
         
         d_val__.symbol_entry = NULL;
         
         
         }
        break;

        case 24:
        {
         
         if(!d_vsp__[-1].string_value)
         report_error("variable name cannot be null", get_line_number());
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[-1].string_value, int_data_type);
         delete d_vsp__[-1].string_value;
         
         }
        break;

        case 25:
        {
         
         if(!d_vsp__[-1].string_value)
         report_error("variable name cannot be null", get_line_number());
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[-1].string_value, float_data_type);
         delete d_vsp__[-1].string_value;
         
         }
        break;

        case 26:
        {
         
         if (!d_vsp__[0].basic_block)
         report_error("Basic block doesn't exist", get_line_number());
         bb_strictly_increasing_order_check(d_val__.basic_block_list, d_vsp__[0].basic_block->get_bb_number());
         d_val__.basic_block_list = d_vsp__[-1].basic_block_list;
         d_val__.basic_block_list->push_back(d_vsp__[0].basic_block);
         
         }
        break;

        case 27:
        {
         
         if (!d_vsp__[0].basic_block)
         report_error("Basic block doesn't exist", get_line_number());
         d_val__.basic_block_list = new list<Basic_Block *>;
         d_val__.basic_block_list->push_back(d_vsp__[0].basic_block);
         
         }
        break;

        case 28:
        {
         
         d_val__.basic_block = new Basic_Block(d_vsp__[-2].integer_value,*d_vsp__[0].ast_list);
         
         }
        break;

        case 29:
        {
         
         d_val__.ast_list = d_vsp__[0].ast_list;
         
         }
        break;

        case 30:
        {
         
         Ast * ret = new Return_Ast();
         if (d_vsp__[-2].ast_list)
         d_val__.ast_list = d_vsp__[-2].ast_list;
         else
         d_val__.ast_list = new list<Ast *>;
         d_val__.ast_list->push_back(ret);
         
         }
        break;

        case 32:
        {
         
         if (d_vsp__[-1].ast_list)
         d_val__.ast_list = d_vsp__[-1].ast_list;
         else
         d_val__.ast_list = new list<Ast *>;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         
         }
        break;

        case 33:
        {
         
         if (d_vsp__[-1].ast_list)
         d_val__.ast_list = d_vsp__[-1].ast_list;
         else
         d_val__.ast_list = new list<Ast *>;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         
        }
        break;

        case 34:
        {
         
         d_val__.ast = new Conditional_Goto_Ast(d_vsp__[-8].ast, d_vsp__[-5].integer_value, d_vsp__[-1].integer_value);
         
        }
        break;

        case 35:
        {
         
         d_val__.ast = new Unconditional_Goto_Ast(d_vsp__[-1].integer_value);
         
         
         }
        break;

        case 36:
        {
         
         d_val__.ast = d_vsp__[0].ast;
         
         }
        break;

        case 37:
        {
         
         d_val__.ast = new Relation_Expression_Ast( d_vsp__[-2].ast, d_vsp__[0].ast, relop::LE);
         
         }
        break;

        case 38:
        {
         
         d_val__.ast = new Relation_Expression_Ast((Ast *) d_vsp__[-2].ast, (Ast *) d_vsp__[0].ast, relop::GE);
         
         }
        break;

        case 39:
        {
         
         d_val__.ast = new Relation_Expression_Ast((Ast *) d_vsp__[-2].ast, (Ast *) d_vsp__[0].ast, relop::LT);
         
         }
        break;

        case 40:
        {
         
         d_val__.ast = new Relation_Expression_Ast((Ast *) d_vsp__[-2].ast, (Ast *) d_vsp__[0].ast, relop::GT);
         
         }
        break;

        case 41:
        {
         
         d_val__.ast= new Arithmetic_Expression_Ast((Ast *) d_vsp__[-2].ast, (Ast *) d_vsp__[0].ast, arithop::PLUS);
         
         }
        break;

        case 42:
        {
         
         d_val__.ast=new Arithmetic_Expression_Ast((Ast *) d_vsp__[-2].ast, (Ast *) d_vsp__[0].ast, arithop::MINUS);
         
         }
        break;

        case 43:
        {
         
         d_val__.ast=new Arithmetic_Expression_Ast((Ast *) d_vsp__[-2].ast, (Ast *) d_vsp__[0].ast, arithop::MULT);
         
         }
        break;

        case 44:
        {
         
         d_val__.ast=new Arithmetic_Expression_Ast((Ast *) d_vsp__[-2].ast, (Ast *) d_vsp__[0].ast, arithop::DIV);
         
         }
        break;

        case 45:
        {
         
         d_val__.ast=d_vsp__[0].ast;
         
         }
        break;

        case 46:
        {
         
         d_val__.ast=d_vsp__[-1].ast;
         
         }
        break;

        case 47:
        {
         
         d_val__.ast=d_vsp__[0].ast;
         
         }
        break;

        case 48:
        {
         d_val__.ast = new Unary_Expression_Ast((Ast *)d_vsp__[0].ast);
         }
        break;

        case 49:
        {
         d_val__.ast = new Unary_Expression_Ast((Ast *)d_vsp__[-1].ast);
         }
        break;

        case 50:
        {
         
         d_val__.ast=new Typecast_Ast((Ast *) d_vsp__[-1].ast, typecast_type::FLOAT);
         
         }
        break;

        case 51:
        {
         
         d_val__.ast=new Typecast_Ast((Ast *) d_vsp__[-1].ast, typecast_type::DOUBLE);
         
         }
        break;

        case 52:
        {
         
         d_val__.ast=new Typecast_Ast((Ast *) d_vsp__[-1].ast, typecast_type::INTEGER);
         
         }
        break;

        case 53:
        {
         
         d_val__.ast=new Typecast_Ast((Ast *) d_vsp__[0].ast, typecast_type::FLOAT);
         
         }
        break;

        case 54:
        {
         
         d_val__.ast=new Typecast_Ast((Ast *) d_vsp__[0].ast, typecast_type::DOUBLE);
         
         }
        break;

        case 55:
        {
         
         d_val__.ast=new Typecast_Ast((Ast *) d_vsp__[0].ast, typecast_type::INTEGER);
         
         }
        break;

        case 56:
        {
         
         d_val__.ast=d_vsp__[0].ast;
         
         }
        break;

        case 57:
        {
         
         d_val__.ast = new Relation_Expression_Ast((Ast *) d_vsp__[-2].ast, (Ast *) d_vsp__[0].ast, relop::NE);
         
         }
        break;

        case 58:
        {
         
         d_val__.ast = new Relation_Expression_Ast((Ast *) d_vsp__[-2].ast, (Ast *) d_vsp__[0].ast, relop::EQ);
         
         }
        break;

        case 59:
        {
         
         d_val__.ast_list = NULL;
         
         
         }
        break;

        case 60:
        {
         
         if (!d_vsp__[-1].ast_list)
         d_val__.ast_list = new list<Ast *>;
         else
         d_val__.ast_list = d_vsp__[-1].ast_list;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         
         }
        break;

        case 61:
        {
         
         d_val__.ast_list= new list<Ast *>;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         
         }
        break;

        case 62:
        {
         
         if (d_vsp__[-2].ast_list) {
         d_val__.ast_list = d_vsp__[-2].ast_list;
         }
         else
         d_val__.ast_list = new list<Ast *>;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         
         }
        break;

        case 63:
        {
         
         d_val__.ast_list=new list<Ast *>;
         d_val__.ast_list->clear();
         
         }
        break;

        case 64:
        {
         
         if (!d_vsp__[-3].ast || !d_vsp__[-1].ast)
         report_error("lhs/rhs cannot be null", get_line_number());
         d_val__.ast = new Assignment_Ast(d_vsp__[-3].ast, d_vsp__[-1].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         
         }
        break;

        case 65:
        {
         
         d_val__.ast = new Function_Call_Ast(*d_vsp__[-2].ast_list,program_object.get_procedure(*d_vsp__[-4].string_value));
         
         }
        break;

        case 66:
        {
         #if 0
         Symbol_Table_Entry var_table_entry;
         if(!d_vsp__[0].string_value)
         report_error("variable name cannot be null", get_line_number());
         if (current_procedure->variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = current_procedure->get_symbol_table_entry(*d_vsp__[0].string_value);
         else if (program_object.variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = program_object.get_symbol_table_entry(*d_vsp__[0].string_value);
         else
         report_error("Variable has not been declared", get_line_number());
         d_val__.ast = new Name_Ast(*d_vsp__[0].string_value, var_table_entry);
         delete d_vsp__[0].string_value;
         #endif
         }
        break;

        case 67:
        {
         #if 0
         d_val__.ast=d_vsp__[0].ast;
         #endif
         }
        break;

        case 68:
        {
         #if 0
         d_val__.ast = new Function_Call_Ast(*d_vsp__[-1].ast_list,program_object.get_procedure(*d_vsp__[-3].string_value));
         #endif
         }
        break;

        case 69:
        {
         
         d_val__.ast = new Number_Ast<int>(d_vsp__[0].integer_value, int_data_type);
         
         }
        break;

        case 70:
        {
         
         d_val__.ast = new Number_Ast<float>(d_vsp__[0].float_value, float_data_type);
         
         }
        break;

        case 71:
        {
         
         d_val__.ast = d_vsp__[0].ast;
         
         }
        break;

        case 72:
        {
         
         d_val__.ast = d_vsp__[0].ast;
         
         }
        break;

    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

